# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'to_pic2_doNDjn.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

# to create backgrounds.py use Pyrcc5 backgrounds.qrc -o backgrounds.py in \venv\Scripts
import backgrounds

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMaximumSize(QSize(1024, 768))
        MainWindow.setStyleSheet(u"background-color:rgb(30,44,57);")
        self.verticalLayoutWidget = QWidget(MainWindow)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 1001, 751))
        self.MainLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.MainLayout.setObjectName(u"MainLayout")
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainFrame = QFrame(self.verticalLayoutWidget)
        self.MainFrame.setObjectName(u"MainFrame")
        self.MainFrame.setAutoFillBackground(False)
        self.MainFrame.setStyleSheet(u"background-color: rgb(30,44,57);")
        self.MainFrame.setFrameShape(QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QFrame.Raised)
        self.Col1 = QFrame(self.MainFrame)
        self.Col1.setObjectName(u"Col1")
        self.Col1.setGeometry(QRect(10, 50, 160, 51))
        font = QFont()
        font.setPointSize(11)
        self.Col1.setFont(font)
        self.Col1.setFrameShape(QFrame.StyledPanel)
        self.Col1.setFrameShadow(QFrame.Raised)
        self.Col1_label = QLabel(self.Col1)
        self.Col1_label.setObjectName(u"Col1_label")
        self.Col1_label.setGeometry(QRect(10, 10, 121, 31))
        font1 = QFont()
        font1.setFamily(u"Garamond")
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setWeight(75)
        self.Col1_label.setFont(font1)
        self.Col1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col2 = QFrame(self.MainFrame)
        self.Col2.setObjectName(u"Col2")
        self.Col2.setGeometry(QRect(171, 50, 90, 51))
        self.Col2.setFrameShape(QFrame.StyledPanel)
        self.Col2.setFrameShadow(QFrame.Raised)
        self.Col3 = QFrame(self.MainFrame)
        self.Col3.setObjectName(u"Col3")
        self.Col3.setGeometry(QRect(262, 50, 90, 51))
        self.Col3.setFrameShape(QFrame.StyledPanel)
        self.Col3.setFrameShadow(QFrame.Raised)
        self.Col4 = QFrame(self.MainFrame)
        self.Col4.setObjectName(u"Col4")
        self.Col4.setGeometry(QRect(353, 50, 90, 51))
        self.Col4.setFrameShape(QFrame.StyledPanel)
        self.Col4.setFrameShadow(QFrame.Raised)
        self.Col5 = QFrame(self.MainFrame)
        self.Col5.setObjectName(u"Col5")
        self.Col5.setGeometry(QRect(444, 50, 90, 51))
        self.Col5.setFrameShape(QFrame.StyledPanel)
        self.Col5.setFrameShadow(QFrame.Raised)
        self.Col5_label = QLabel(self.Col5)
        self.Col5_label.setObjectName(u"Col5_label")
        self.Col5_label.setGeometry(QRect(-1, 10, 81, 30))
        self.Col5_label.setFont(font1)
        self.Col5_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col5_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col6 = QFrame(self.MainFrame)
        self.Col6.setObjectName(u"Col6")
        self.Col6.setGeometry(QRect(535, 50, 90, 51))
        self.Col6.setFrameShape(QFrame.StyledPanel)
        self.Col6.setFrameShadow(QFrame.Raised)
        self.Col7 = QFrame(self.MainFrame)
        self.Col7.setObjectName(u"Col7")
        self.Col7.setGeometry(QRect(626, 50, 90, 51))
        self.Col7.setFrameShape(QFrame.StyledPanel)
        self.Col7.setFrameShadow(QFrame.Raised)
        self.Col7_label = QLabel(self.Col7)
        self.Col7_label.setObjectName(u"Col7_label")
        self.Col7_label.setGeometry(QRect(10, 10, 70, 30))
        self.Col7_label.setFont(font1)
        self.Col7_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col7_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col8 = QFrame(self.MainFrame)
        self.Col8.setObjectName(u"Col8")
        self.Col8.setGeometry(QRect(717, 50, 90, 51))
        self.Col8.setFrameShape(QFrame.StyledPanel)
        self.Col8.setFrameShadow(QFrame.Raised)
        self.Col8_label = QLabel(self.Col8)
        self.Col8_label.setObjectName(u"Col8_label")
        self.Col8_label.setGeometry(QRect(10, 10, 70, 30))
        self.Col8_label.setFont(font1)
        self.Col8_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col8_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col91 = QFrame(self.MainFrame)
        self.Col91.setObjectName(u"Col91")
        self.Col91.setGeometry(QRect(808, 50, 90, 51))
        self.Col91.setAutoFillBackground(False)
        self.Col91.setStyleSheet(u"color:rgb(100, 100, 100)")
        self.Col91.setFrameShape(QFrame.StyledPanel)
        self.Col91.setFrameShadow(QFrame.Raised)
        self.Col91_label = QLabel(self.Col91)
        self.Col91_label.setObjectName(u"Col91_label")
        self.Col91_label.setGeometry(QRect(10, 10, 70, 30))
        self.Col91_label.setFont(font1)
        self.Col91_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col91_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col4_Row1 = QFrame(self.MainFrame)
        self.Col4_Row1.setObjectName(u"Col4_Row1")
        self.Col4_Row1.setGeometry(QRect(353, 110, 90, 30))
        self.Col4_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col4_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col4_Row1.setFrameShadow(QFrame.Raised)
        self.Col4_Row1_label = QLabel(self.Col4_Row1)
        self.Col4_Row1_label.setObjectName(u"Col4_Row1_label")
        self.Col4_Row1_label.setGeometry(QRect(0, 0, 80, 31))
        self.Col4_Row1_label.setFont(font1)
        self.Col4_Row1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col4_Row1_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col8_Row1 = QFrame(self.MainFrame)
        self.Col8_Row1.setObjectName(u"Col8_Row1")
        self.Col8_Row1.setGeometry(QRect(717, 110, 90, 30))
        self.Col8_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col8_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col8_Row1.setFrameShadow(QFrame.Raised)
        self.Col8_Row1_label = QLabel(self.Col8_Row1)
        self.Col8_Row1_label.setObjectName(u"Col8_Row1_label")
        self.Col8_Row1_label.setGeometry(QRect(0, 0, 80, 31))
        self.Col8_Row1_label.setFont(font1)
        self.Col8_Row1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col8_Row1_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col5_Row1 = QFrame(self.MainFrame)
        self.Col5_Row1.setObjectName(u"Col5_Row1")
        self.Col5_Row1.setGeometry(QRect(444, 110, 90, 30))
        self.Col5_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col5_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col5_Row1.setFrameShadow(QFrame.Raised)
        self.Col5_Row1_label = QLabel(self.Col5_Row1)
        self.Col5_Row1_label.setObjectName(u"Col5_Row1_label")
        self.Col5_Row1_label.setGeometry(QRect(0, 0, 80, 31))
        self.Col5_Row1_label.setFont(font1)
        self.Col5_Row1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col5_Row1_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col91_Row1 = QFrame(self.MainFrame)
        self.Col91_Row1.setObjectName(u"Col91_Row1")
        self.Col91_Row1.setGeometry(QRect(808, 110, 90, 30))
        self.Col91_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col91_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col91_Row1.setFrameShadow(QFrame.Raised)
        self.Col91_Row1_label = QLabel(self.Col91_Row1)
        self.Col91_Row1_label.setObjectName(u"Col91_Row1_label")
        self.Col91_Row1_label.setGeometry(QRect(0, 0, 80, 31))
        self.Col91_Row1_label.setFont(font1)
        self.Col91_Row1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col91_Row1_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col6_Row1 = QFrame(self.MainFrame)
        self.Col6_Row1.setObjectName(u"Col6_Row1")
        self.Col6_Row1.setGeometry(QRect(535, 110, 90, 30))
        self.Col6_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col6_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col6_Row1.setFrameShadow(QFrame.Raised)
        self.Col6_Row1_label = QLabel(self.Col6_Row1)
        self.Col6_Row1_label.setObjectName(u"Col6_Row1_label")
        self.Col6_Row1_label.setGeometry(QRect(0, 0, 80, 31))
        self.Col6_Row1_label.setFont(font1)
        self.Col6_Row1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col6_Row1_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col2_Row1 = QFrame(self.MainFrame)
        self.Col2_Row1.setObjectName(u"Col2_Row1")
        self.Col2_Row1.setGeometry(QRect(171, 110, 90, 30))
        self.Col2_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col2_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col2_Row1.setFrameShadow(QFrame.Raised)
        self.Col2_Row1_label = QLabel(self.Col2_Row1)
        self.Col2_Row1_label.setObjectName(u"Col2_Row1_label")
        self.Col2_Row1_label.setGeometry(QRect(0, 0, 80, 31))
        self.Col2_Row1_label.setFont(font1)
        self.Col2_Row1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col2_Row1_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col1_Row1 = QFrame(self.MainFrame)
        self.Col1_Row1.setObjectName(u"Col1_Row1")
        self.Col1_Row1.setGeometry(QRect(10, 110, 160, 30))
        self.Col1_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col1_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col1_Row1.setFrameShadow(QFrame.Raised)
        self.Col1_Row1_label = QLabel(self.Col1_Row1)
        self.Col1_Row1_label.setObjectName(u"Col1_Row1_label")
        self.Col1_Row1_label.setGeometry(QRect(10, 0, 120, 30))
        self.Col1_Row1_label.setFont(font1)
        self.Col1_Row1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col7_Row1 = QFrame(self.MainFrame)
        self.Col7_Row1.setObjectName(u"Col7_Row1")
        self.Col7_Row1.setGeometry(QRect(626, 110, 90, 30))
        self.Col7_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col7_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col7_Row1.setFrameShadow(QFrame.Raised)
        self.Col7_Row1_label = QLabel(self.Col7_Row1)
        self.Col7_Row1_label.setObjectName(u"Col7_Row1_label")
        self.Col7_Row1_label.setGeometry(QRect(0, 0, 80, 31))
        self.Col7_Row1_label.setFont(font1)
        self.Col7_Row1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col7_Row1_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col3_Row1 = QFrame(self.MainFrame)
        self.Col3_Row1.setObjectName(u"Col3_Row1")
        self.Col3_Row1.setGeometry(QRect(262, 110, 90, 30))
        self.Col3_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col3_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col3_Row1.setFrameShadow(QFrame.Raised)
        self.Col3_Row1_label = QLabel(self.Col3_Row1)
        self.Col3_Row1_label.setObjectName(u"Col3_Row1_label")
        self.Col3_Row1_label.setGeometry(QRect(0, 0, 80, 31))
        self.Col3_Row1_label.setFont(font1)
        self.Col3_Row1_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col3_Row1_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col92 = QFrame(self.MainFrame)
        self.Col92.setObjectName(u"Col92")
        self.Col92.setGeometry(QRect(899, 50, 90, 51))
        self.Col92.setFrameShape(QFrame.StyledPanel)
        self.Col92.setFrameShadow(QFrame.Raised)
        self.Col92_label = QLabel(self.Col92)
        self.Col92_label.setObjectName(u"Col92_label")
        self.Col92_label.setGeometry(QRect(10, 10, 70, 30))
        self.Col92_label.setFont(font1)
        self.Col92_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col92_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col92_Row1 = QFrame(self.MainFrame)
        self.Col92_Row1.setObjectName(u"Col92_Row1")
        self.Col92_Row1.setGeometry(QRect(899, 110, 90, 30))
        self.Col92_Row1.setStyleSheet(u"background-color: rgb(44,60,75)")
        self.Col92_Row1.setFrameShape(QFrame.StyledPanel)
        self.Col92_Row1.setFrameShadow(QFrame.Raised)
        self.Col1_Row92_label = QLabel(self.Col92_Row1)
        self.Col1_Row92_label.setObjectName(u"Col1_Row92_label")
        self.Col1_Row92_label.setGeometry(QRect(0, 0, 80, 31))
        self.Col1_Row92_label.setFont(font1)
        self.Col1_Row92_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col1_Row92_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Col1_Row2 = QFrame(self.MainFrame)
        self.Col1_Row2.setObjectName(u"Col1_Row2")
        self.Col1_Row2.setGeometry(QRect(10, 151, 161, 590))
        self.Col1_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col1_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col1_Row2.setFrameShadow(QFrame.Raised)
        self.Col1_Row2_label = QLabel(self.Col1_Row2)
        self.Col1_Row2_label.setObjectName(u"Col1_Row2_label")
        self.Col1_Row2_label.setGeometry(QRect(0, 0, 160, 590))
        font2 = QFont()
        font2.setFamily(u"Garamond")
        font2.setPointSize(11)
        font2.setBold(True)
        font2.setWeight(75)
        font2.setKerning(True)
        self.Col1_Row2_label.setFont(font2)
        self.Col1_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col1_Row2_label.setLineWidth(0)
        self.Col1_Row2_label.setTextFormat(Qt.AutoText)
        self.Col1_Row2_label.setScaledContents(True)
        self.Col1_Row2_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.Col1_Row2_label.setWordWrap(False)
        self.Col1_Row2_label.setMargin(1)
        self.Col1_Row2_label.setIndent(1)
        self.Col2_Row2 = QFrame(self.MainFrame)
        self.Col2_Row2.setObjectName(u"Col2_Row2")
        self.Col2_Row2.setGeometry(QRect(171, 151, 90, 590))
        self.Col2_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col2_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col2_Row2.setFrameShadow(QFrame.Raised)
        self.Col2_Row2_label = QLabel(self.Col2_Row2)
        self.Col2_Row2_label.setObjectName(u"Col2_Row2_label")
        self.Col2_Row2_label.setGeometry(QRect(0, 0, 90, 590))
        self.Col2_Row2_label.setFont(font2)
        self.Col2_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col2_Row2_label.setLineWidth(0)
        self.Col2_Row2_label.setTextFormat(Qt.AutoText)
        self.Col2_Row2_label.setScaledContents(True)
        self.Col2_Row2_label.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.Col2_Row2_label.setWordWrap(False)
        self.Col2_Row2_label.setMargin(1)
        self.Col2_Row2_label.setIndent(1)
        self.Col3_Row2 = QFrame(self.MainFrame)
        self.Col3_Row2.setObjectName(u"Col3_Row2")
        self.Col3_Row2.setGeometry(QRect(262, 151, 90, 590))
        self.Col3_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col3_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col3_Row2.setFrameShadow(QFrame.Raised)
        self.Col3_Row2_label = QLabel(self.Col3_Row2)
        self.Col3_Row2_label.setObjectName(u"Col3_Row2_label")
        self.Col3_Row2_label.setGeometry(QRect(0, 0, 90, 590))
        self.Col3_Row2_label.setFont(font2)
        self.Col3_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col3_Row2_label.setLineWidth(0)
        self.Col3_Row2_label.setTextFormat(Qt.AutoText)
        self.Col3_Row2_label.setScaledContents(True)
        self.Col3_Row2_label.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.Col3_Row2_label.setWordWrap(False)
        self.Col3_Row2_label.setMargin(1)
        self.Col3_Row2_label.setIndent(1)
        self.Col4_Row2 = QFrame(self.MainFrame)
        self.Col4_Row2.setObjectName(u"Col4_Row2")
        self.Col4_Row2.setGeometry(QRect(353, 151, 90, 590))
        self.Col4_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col4_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col4_Row2.setFrameShadow(QFrame.Raised)
        self.Col4_Row2_label = QLabel(self.Col4_Row2)
        self.Col4_Row2_label.setObjectName(u"Col4_Row2_label")
        self.Col4_Row2_label.setGeometry(QRect(0, 0, 90, 590))
        self.Col4_Row2_label.setFont(font2)
        self.Col4_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col4_Row2_label.setLineWidth(0)
        self.Col4_Row2_label.setTextFormat(Qt.AutoText)
        self.Col4_Row2_label.setScaledContents(True)
        self.Col4_Row2_label.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.Col4_Row2_label.setWordWrap(False)
        self.Col4_Row2_label.setMargin(1)
        self.Col4_Row2_label.setIndent(1)
        self.Col5_Row2 = QFrame(self.MainFrame)
        self.Col5_Row2.setObjectName(u"Col5_Row2")
        self.Col5_Row2.setGeometry(QRect(444, 151, 90, 590))
        self.Col5_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col5_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col5_Row2.setFrameShadow(QFrame.Raised)
        self.Col5_Row2_label = QLabel(self.Col5_Row2)
        self.Col5_Row2_label.setObjectName(u"Col5_Row2_label")
        self.Col5_Row2_label.setGeometry(QRect(0, 0, 90, 590))
        self.Col5_Row2_label.setFont(font2)
        self.Col5_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col5_Row2_label.setLineWidth(0)
        self.Col5_Row2_label.setTextFormat(Qt.AutoText)
        self.Col5_Row2_label.setScaledContents(True)
        self.Col5_Row2_label.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.Col5_Row2_label.setWordWrap(False)
        self.Col5_Row2_label.setMargin(1)
        self.Col5_Row2_label.setIndent(1)
        self.Col6_Row2 = QFrame(self.MainFrame)
        self.Col6_Row2.setObjectName(u"Col6_Row2")
        self.Col6_Row2.setGeometry(QRect(535, 151, 90, 590))
        self.Col6_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col6_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col6_Row2.setFrameShadow(QFrame.Raised)
        self.Col6_Row2_label = QLabel(self.Col6_Row2)
        self.Col6_Row2_label.setObjectName(u"Col6_Row2_label")
        self.Col6_Row2_label.setGeometry(QRect(0, 0, 90, 590))
        self.Col6_Row2_label.setFont(font2)
        self.Col6_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col6_Row2_label.setLineWidth(0)
        self.Col6_Row2_label.setTextFormat(Qt.AutoText)
        self.Col6_Row2_label.setScaledContents(True)
        self.Col6_Row2_label.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.Col6_Row2_label.setWordWrap(False)
        self.Col6_Row2_label.setMargin(1)
        self.Col6_Row2_label.setIndent(1)
        self.Col7_Row2 = QFrame(self.MainFrame)
        self.Col7_Row2.setObjectName(u"Col7_Row2")
        self.Col7_Row2.setGeometry(QRect(626, 151, 90, 590))
        self.Col7_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col7_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col7_Row2.setFrameShadow(QFrame.Raised)
        self.Col7_Row2_label = QLabel(self.Col7_Row2)
        self.Col7_Row2_label.setObjectName(u"Col7_Row2_label")
        self.Col7_Row2_label.setGeometry(QRect(0, 0, 90, 590))
        self.Col7_Row2_label.setFont(font2)
        self.Col7_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col7_Row2_label.setLineWidth(0)
        self.Col7_Row2_label.setTextFormat(Qt.AutoText)
        self.Col7_Row2_label.setScaledContents(True)
        self.Col7_Row2_label.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.Col7_Row2_label.setWordWrap(False)
        self.Col7_Row2_label.setMargin(1)
        self.Col7_Row2_label.setIndent(1)
        self.Col8_Row2 = QFrame(self.MainFrame)
        self.Col8_Row2.setObjectName(u"Col8_Row2")
        self.Col8_Row2.setGeometry(QRect(717, 151, 90, 590))
        self.Col8_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col8_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col8_Row2.setFrameShadow(QFrame.Raised)
        self.Col8_Row2_label = QLabel(self.Col8_Row2)
        self.Col8_Row2_label.setObjectName(u"Col8_Row2_label")
        self.Col8_Row2_label.setGeometry(QRect(0, 0, 90, 590))
        self.Col8_Row2_label.setFont(font2)
        self.Col8_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col8_Row2_label.setLineWidth(0)
        self.Col8_Row2_label.setTextFormat(Qt.AutoText)
        self.Col8_Row2_label.setScaledContents(True)
        self.Col8_Row2_label.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.Col8_Row2_label.setWordWrap(False)
        self.Col8_Row2_label.setMargin(1)
        self.Col8_Row2_label.setIndent(1)
        self.Col91_Row2 = QFrame(self.MainFrame)
        self.Col91_Row2.setObjectName(u"Col91_Row2")
        self.Col91_Row2.setGeometry(QRect(808, 151, 90, 590))
        self.Col91_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col91_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col91_Row2.setFrameShadow(QFrame.Raised)
        self.Col91_Row2_label = QLabel(self.Col91_Row2)
        self.Col91_Row2_label.setObjectName(u"Col91_Row2_label")
        self.Col91_Row2_label.setGeometry(QRect(0, 0, 90, 590))
        self.Col91_Row2_label.setFont(font2)
        self.Col91_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col91_Row2_label.setLineWidth(0)
        self.Col91_Row2_label.setTextFormat(Qt.AutoText)
        self.Col91_Row2_label.setScaledContents(True)
        self.Col91_Row2_label.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.Col91_Row2_label.setWordWrap(False)
        self.Col91_Row2_label.setMargin(1)
        self.Col91_Row2_label.setIndent(1)
        self.Col92_Row2 = QFrame(self.MainFrame)
        self.Col92_Row2.setObjectName(u"Col92_Row2")
        self.Col92_Row2.setGeometry(QRect(899, 151, 90, 590))
        self.Col92_Row2.setStyleSheet(u"background-image: url(:/backrgounds/background.png);")
        self.Col92_Row2.setFrameShape(QFrame.StyledPanel)
        self.Col92_Row2.setFrameShadow(QFrame.Raised)
        self.Col92_Row2_label = QLabel(self.Col92_Row2)
        self.Col92_Row2_label.setObjectName(u"Col92_Row2_label")
        self.Col92_Row2_label.setGeometry(QRect(0, 0, 90, 590))
        self.Col92_Row2_label.setFont(font2)
        self.Col92_Row2_label.setStyleSheet(u"color: rgb(179,199,209)")
        self.Col92_Row2_label.setLineWidth(0)
        self.Col92_Row2_label.setTextFormat(Qt.AutoText)
        self.Col92_Row2_label.setScaledContents(True)
        self.Col92_Row2_label.setAlignment(Qt.AlignRight|Qt.AlignTop|Qt.AlignTrailing)
        self.Col92_Row2_label.setWordWrap(False)
        self.Col92_Row2_label.setMargin(1)
        self.Col92_Row2_label.setIndent(1)

        self.MainLayout.addWidget(self.MainFrame)


        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Form", None))
        self.Col1_label.setText(QCoreApplication.translate("MainWindow", u"\u0411\u0440\u043e\u043a\u0435\u0440\u0441\u043a\u0438\u0439 \u0441\u0447\u0435\u0442", None))
        self.Col5_label.setText(QCoreApplication.translate("MainWindow", u"1 137 123,20", None))
        self.Col7_label.setText(QCoreApplication.translate("MainWindow", u"100 000,20", None))
        self.Col8_label.setText(QCoreApplication.translate("MainWindow", u"10%", None))
        self.Col91_label.setText(QCoreApplication.translate("MainWindow", u"10 000,20", None))
        self.Col4_Row1_label.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0440\u0435\u0434\u043d\u044f\u044f", None))
        self.Col8_Row1_label.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0445\u043e\u0434 %", None))
        self.Col5_Row1_label.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c", None))
        self.Col91_Row1_label.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430 \u0434\u0435\u043d\u044c", None))
        self.Col6_Row1_label.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u043b\u044f", None))
        self.Col2_Row1_label.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u043e", None))
        self.Col1_Row1_label.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435", None))
        self.Col7_Row1_label.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0445\u043e\u0434", None))
        self.Col3_Row1_label.setText(QCoreApplication.translate("MainWindow", u"\u0426\u0435\u043d\u0430", None))
        self.Col92_label.setText(QCoreApplication.translate("MainWindow", u"2%", None))
        self.Col1_Row92_label.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430 \u0434\u0435\u043d\u044c %", None))
        self.Col1_Row2_label.setText("")
        self.Col2_Row2_label.setText("")
        self.Col3_Row2_label.setText("")
        self.Col4_Row2_label.setText("")
        self.Col5_Row2_label.setText("")
        self.Col6_Row2_label.setText("")
        self.Col7_Row2_label.setText("")
        self.Col8_Row2_label.setText("")
        self.Col91_Row2_label.setText("")
        self.Col92_Row2_label.setText("")
    # retranslateUi
